#!/bin/bash

user_id=$(id -u)

if [ $user_id -ne 0 ]; then
   echo "run with root user"
   exit 1
fi

VALIDATE(){
    if [ $1 -ne 0 ]; then
        echo "$2 is fail"
        exit 1

    else
        echo "$2 is success"
    
    fi
}


dnf install nginx -y
VALIDATE $? "installing nginx"

dnf install mysql -y
VALIDATE $? "installing mysql"